### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'judge'

### ISSUE THREAD

**Issue by ypyean** [constverum/ProxyBroker#1]
Hello,

I tried your code and there is an error:  TypeError: __init__() got multiple values for argument 'judge'. The traceback as follows:

Traceback (most recent call last):
  File "./test.py", line 77, in <module>
    start(500)
  File "./test.py", line 59, in start
    worker.start()
  File "/proxychecker/pyproxychecker/checker.py", line 100, in start
    self.loop.run_until_complete(self.run())
  File "/anaconda3/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
    return future.result()
  File "/anaconda3/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/anaconda3/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/proxychecker/pyproxychecker/checker.py", line 109, in run
    await self.clear_proxies()
  File "/proxychecker/pyproxychecker/checker.py", line 171, in clear_proxies
    for p in self.proxies['input']]
  File "/proxychecker/pyproxychecker/checker.py", line 171, in <listcomp>
    for p in self.proxies['input']]
TypeError: __init__() got multiple values for argument 'judge'

**Comment by constverum** [comment]
Hello!
Current code - a preview version.
In a couple of days will be released a beta version (with finding proxy and error correction).

**Comment by constverum** [comment]
Try the new version
