### ISSUE TITLE
cant't install proxybroker 0.3.2 from direct github - python multi version

### ISSUE THREAD

**Issue by cbastienbaron** [constverum/ProxyBroker#114]
Hi, 

I'm pretty sure this is a shit from come from me but if i follow install guide i.e. (`pip3 install -U git+https://github.com/constverum/ProxyBroker.git`) 

it's install files in my home (/home/toto/.local/bin/proxybroker) 

i try to execute bin but i have the stack trace bellow 

```python
/home/toto/.local/bin/proxybroker
Traceback (most recent call last):
  File "/home/toto/.local/bin/proxybroker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'proxybroker==0.3.2' distribution was not found and is required by the application
```

I suspect multi version of python present of server cause this issue, guys have you an idea about this ?

**Comment by constverum** [comment]
Need a little more detail. What OS and python version do you use?

Did you try to install from pypi directly?
```pip install --upgrade --force-reinstall --ignore-installed proxybroker```
In this case, the error still occurs?

**Comment by cbastienbaron** [comment]
Hoooo thanks very much, that's resolved issue :+1: 

my env is debian 9 and python3.5 (i have also 2.7. and co)
Ho i see, it's install requirements on `/usr/local/lib/python3.5/dist-packages/proxybroker` instead of home user 

You made my day @constverum :+1:
