### ISSUE TITLE
ImportError: cannot import name 'Coroutine'

### ISSUE THREAD

**Issue by gMan1990** [constverum/ProxyBroker#119]
* Python 3.5.2
* pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)
* proxybroker-0.3.2
```
Traceback (most recent call last):
  File "/usr/local/bin/proxybroker", line 7, in <module>
    from proxybroker.cli import cli
  File "/usr/local/lib/python3.5/dist-packages/proxybroker/__init__.py", line 28, in <module>
    from .proxy import Proxy  # noqa
  File "/usr/local/lib/python3.5/dist-packages/proxybroker/proxy.py", line 16, in <module>
    from .resolver import Resolver
  File "/usr/local/lib/python3.5/dist-packages/proxybroker/resolver.py", line 9, in <module>
    import aiohttp
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 12, in <module>
    from typing import (  # noqa
ImportError: cannot import name 'Coroutine'
```
```
aiodns==2.0.0
aiohttp==3.5.4
async-timeout==3.0.1
attrs==19.1.0
blinker==1.3
cffi==1.12.2
chardet==2.3.0
Click==7.0
cloud-init==0.7.8
command-not-found==0.3
configobj==5.0.6
cryptography==1.2.3
cycler==0.10.0
Flask==1.0.2
Flask-SQLAlchemy==2.3.2
idna==2.0
idna-ssl==1.1.0
itsdangerous==1.1.0
jieba==0.39
Jinja2==2.10.1
jsonpatch==1.10
jsonpointer==1.9
kiwisolver==1.0.1
language-selector==0.1
MarkupSafe==0.23
matplotlib==3.0.3
maxminddb==1.4.1
multidict==4.5.2
numpy==1.16.2
oauthlib==1.0.3
prettytable==0.7.2
proxybroker==0.3.2
pyasn1==0.1.9
pycares==3.0.0
pycparser==2.19
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
pyparsing==2.4.0
pyserial==3.0.1
python-apt==1.1.0b1
python-dateutil==2.8.0
python-debian==0.1.27
python-systemd==231
PyYAML==3.11
requests==2.9.1
scikit-learn==0.20.3
scipy==1.2.1
six==1.10.0
sklearn==0.0
SQLAlchemy==1.3.2
ssh-import-id==5.5
typing==3.6.6
typing-extensions==3.7.2
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
uWSGI==2.0.18
Werkzeug==0.15.2
yarl==1.3.0
```

**Comment by constverum** [comment]
Try to update python to **3.5.3+**

> **aiohttp** 3.5.4 requires: **Python >=3.5.3**
