### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by MaxPlayBR** [constverum/ProxyBroker#124]
```
$ proxybroker
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/proxybroker", line 6, in <module>
    from proxybroker.cli import cli
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/proxybroker/__init__.py", line 28, in <module>
    from .proxy import Proxy  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/proxybroker/proxy.py", line 16, in <module>
    from .resolver import Resolver
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/proxybroker/resolver.py", line 8, in <module>
    import aiodns
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/aiodns/__init__.py", line 4, in <module>
    import pycares
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pycares/__init__.py", line 2, in <module>
    from ._cares import ffi as _ffi, lib as _lib
ImportError: dlopen failed: cannot locate symbol "getservbyport_r" referenced by "_cares.cpython-37m.so"...
```
How i solve this error?:persevere:

**Comment by constverum** [comment]
There's no way to solve it. The project just is not designed to work on mobile os. #71 #72 #73

**Comment by fishtamire** [comment]
Me to Please help us
