### ISSUE TITLE
Again Exception "Could not get the external IP"

### ISSUE THREAD

**Issue by Yuraz71** [constverum/ProxyBroker#141]
Can I reopen this issue ?
In last week I be in struggle with "Could not get the external IP" exception.

Traceback (most recent call last):
File "refresh_proxy.py", line 50, in
prox = Proxies(loop)
File "refresh_proxy.py", line 13, in init
self._init_proxies(loop)
File "refresh_proxy.py", line 24, in _init_proxies
loop.run_until_complete(asyncio.wait_for(tasks, 120))
File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
return future.result()
File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
return fut.result()
File "/usr/local/lib/python3.7/dist-packages/proxybroker/api.py", line 173, in find
ip = await self._resolver.get_real_ext_ip()
File "/usr/local/lib/python3.7/dist-packages/proxybroker/resolver.py", line 109, in get_real_ext_ip
raise RuntimeError('Could not get the external IP')
RuntimeError: Could not get the external IP

I found some incomprehensibility in resolver.py.
Maybe you can explain this problem for me, and I will leave everything as it is?

So, in resolver.py I found:
_ip_hosts = [
'https://wtfismyip.com/text',
'http://api.ipify.org/',
'http://ipinfo.io/ip',
'http://ipv4.icanhazip.com/',
'http://myexternalip.com/raw',
'http://ipinfo.io/ip',
'http://ifconfig.io/ip',
]
After that:
host = random.choice(self._ip_hosts)
self._ip_hosts.remove(host)

So, when we remove last item from this list we get exception.
And this is confirmed in practice.
I try refresh proxy list every 5 minutes. After 7th times I always get exception.
I try comment this line in local machine:
self._ip_hosts.remove(host)
and all works is fine.

@constverum, could you explain what is wrong ?

**Comment by paulo20223** [comment]
solution

```
import asyncio
import random

import aiohttp
from proxybroker.resolver import Resolver
from proxybroker.utils import log
class ResolverCustom(Resolver):
    _temp_host = []

    def _pop_random_ip_host(self):

        host = random.choice(self._temp_host)
        self._temp_host.remove(host)
        return host

    async def get_real_ext_ip(self):
        self._temp_host = self._ip_hosts.copy()
        while self._temp_host:
            try:
                timeout = aiohttp.ClientTimeout(total=self._timeout)
                async with aiohttp.ClientSession(
                        timeout=timeout, loop=self._loop
                ) as session, session.get(self._pop_random_ip_host()) as resp:
                    ip = await resp.text()
            except asyncio.TimeoutError:
                pass
            else:
                ip = ip.strip()
                if self.host_is_ip(ip):
                    log.debug('Real external IP: %s', ip)
                    break
        else:
            raise RuntimeError('Could not get the external IP')
        return ip
```


```
 broker = Broker(proxies)
 broker._resolver = ResolverCustom(loop=loop)
```
