### ISSUE TITLE
[bug] RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by gMan1990** [constverum/ProxyBroker#163]
- 1
```plain
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 215, in _check
    self._method, proxy, judge
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 165, in check
    result = await self._check(proxy, proto)
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 241, in _check
    proxy.close()
  File "c:\program files\python37\lib\site-packages\proxybroker\proxy.py", line 332, in close
    self.writer.close()
  File "c:\program files\python37\lib\asyncio\streams.py", line 317, in close
    return self._transport.close()
  File "c:\program files\python37\lib\asyncio\selector_events.py", line 663, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\program files\python37\lib\asyncio\base_events.py", line 691, in call_soon
    self._check_closed()
  File "c:\program files\python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Checker.check at 0x00000293A3674F48>
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 169, in check
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 165, in check
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 241, in _check
  File "c:\program files\python37\lib\site-packages\proxybroker\proxy.py", line 332, in close
  File "c:\program files\python37\lib\asyncio\streams.py", line 317, in close
  File "c:\program files\python37\lib\asyncio\selector_events.py", line 663, in close
  File "c:\program files\python37\lib\asyncio\base_events.py", line 691, in call_soon
  File "c:\program files\python37\lib\asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed
```

- 2
```plain
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 213, in _check
    await proxy.ngtr.negotiate(host=judge.host, ip=judge.ip)
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 165, in check
    result = await self._check(proxy, proto)
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 241, in _check
    proxy.close()
  File "c:\program files\python37\lib\site-packages\proxybroker\proxy.py", line 332, in close
    self.writer.close()
  File "c:\program files\python37\lib\asyncio\streams.py", line 317, in close
    return self._transport.close()
  File "c:\program files\python37\lib\asyncio\selector_events.py", line 663, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\program files\python37\lib\asyncio\base_events.py", line 691, in call_soon
    self._check_closed()
  File "c:\program files\python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Checker.check at 0x00000293A3674CC8>
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 169, in check
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 165, in check
  File "c:\program files\python37\lib\site-packages\proxybroker\checker.py", line 241, in _check
  File "c:\program files\python37\lib\site-packages\proxybroker\proxy.py", line 332, in close
  File "c:\program files\python37\lib\asyncio\streams.py", line 317, in close
  File "c:\program files\python37\lib\asyncio\selector_events.py", line 663, in close
  File "c:\program files\python37\lib\asyncio\base_events.py", line 691, in call_soon
  File "c:\program files\python37\lib\asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by MohamedHmini** [comment]
i'm having the same issue, has it been resolved yet?
