### ISSUE TITLE
Getting error "DeprecationWarning: the imp module is deprecated in favour of importlib" when trying to run Proxybroker

### ISSUE THREAD

**Issue by fenixi0** [constverum/ProxyBroker#170]
Anyone else getting this error? I think it might have happened when I updated some system packages on my ubuntu server.

This is the code I'm trying to run: ~# proxybroker find --types HTTP

And I'm getting this error:

`/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/usr/local/bin/proxybroker", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/proxybroker/cli.py", line 433, in cli
    loop.run_until_complete(asyncio.gather(*tasks, loop=loop))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/proxybroker/api.py", line 173, in find
    ip = await self._resolver.get_real_ext_ip()
  File "/usr/local/lib/python3.6/dist-packages/proxybroker/resolver.py", line 96, in get_real_ext_ip
    timeout = aiohttp.ClientTimeout(total=self._timeout)
AttributeError: module 'aiohttp' has no attribute 'ClientTimeout'
Exception ignored in: <coroutine object handle at 0x7fa311111410>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/proxybroker/cli.py", line 343, in handle
  File "/usr/lib/python3.6/asyncio/queues.py", line 169, in get
  File "/usr/lib/python3.6/asyncio/base_events.py", line 591, in call_soon
  File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
RuntimeError: Event loop is closed
`

Could someone help please?

**Comment by CryptoCoder50** [comment]
Downgrade Python to 3.5.9 and that will work, had a similar issue running python 3.6
