### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Kraaken132** [constverum/ProxyBroker#177]
C:\WINDOWS\system32>proxybroker find --types SOCKS4
c:\program files\python38\lib\site-packages\proxybroker\cli.py:380: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  proxies = asyncio.Queue(loop=loop)
c:\program files\python38\lib\asyncio\queues.py:48: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._finished = locks.Event(loop=loop)
c:\program files\python38\lib\site-packages\proxybroker\api.py:97: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._on_check = asyncio.Queue(maxsize=max_conn, loop=self._loop)
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
From cffi callback <function _sock_state_cb at 0x00000285E98E9040>:
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\program files\python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\program files\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by ziloka** [comment]
This [solution](https://stackoverflow.com/a/59512181) worked for me

**Comment by sangnvnkl** [comment]
I run on Linux worked

**Comment by zzm88** [comment]
This happened on Windows. No problem on macos

**Comment by nsitapara** [comment]
I am running into the same issue as this user, not sure if there is  fix identified.

**Comment by bluet** [comment]
As this project is not maintained by the original developer, we've forked ProxyBroker and continued maintaining the proxybroker2 project since 2020.
- https://github.com/bluet/proxybroker2
- https://github.com/constverum/ProxyBroker/pull/161

If anyone's interested, please join. We need more volunteers. :-)
