### ISSUE TITLE
I'm not sure what i'm doing wrong

### ISSUE THREAD

**Issue by Reverrb** [constverum/ProxyBroker#188]
So whenever I use the program, it gives me this

proxybroker find --types SOCKS5 --lvl High --countries US --strict -l 10             
/home/reverb/.local/lib/python3.9/site-packages/proxybroker/cli.py:380: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  proxies = asyncio.Queue(loop=loop)
/usr/lib/python3.9/asyncio/queues.py:48: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._finished = locks.Event(loop=loop)
/home/reverb/.local/lib/python3.9/site-packages/proxybroker/api.py:97: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._on_check = asyncio.Queue(maxsize=max_conn, loop=self._loop)
<Proxy US 0.13s [SOCKS5] 24.249.199.14:57335>
<Proxy US 0.13s [SOCKS5] 72.210.252.134:46164>
<Proxy US 0.14s [SOCKS5] 184.178.172.25:15291>
<Proxy US 0.14s [SOCKS5] 184.178.172.28:15294>
<Proxy US 0.14s [SOCKS5] 184.178.172.18:15280>
<Proxy US 0.19s [SOCKS5] 184.178.172.5:15303>
<Proxy US 0.32s [SOCKS5] 184.178.172.13:15311>
<Proxy US 0.48s [SOCKS5] 192.169.139.161:8975>
<Proxy US 0.49s [SOCKS5] 72.49.49.11:31034>
<Proxy US 1.21s [SOCKS5] 66.42.224.229:41679>
Exception ignored in: <coroutine object Checker.check at 0x7ff45c3cf540>
Traceback (most recent call last):
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/checker.py", line 164, in check
    result = await self._check(proxy, proto)
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/checker.py", line 237, in _check
    proxy.close()
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/proxy.py", line 332, in close
    self.writer.close()
  File "/usr/lib/python3.9/asyncio/streams.py", line 353, in close
    return self._transport.close()
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 700, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Checker.check at 0x7ff45c55bbc0>
Traceback (most recent call last):
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/checker.py", line 164, in check
    result = await self._check(proxy, proto)
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/checker.py", line 237, in _check
    proxy.close()
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/proxy.py", line 332, in close
    self.writer.close()
  File "/usr/lib/python3.9/asyncio/streams.py", line 353, in close
    return self._transport.close()
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 700, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Checker.check at 0x7ff45c55b4c0>
Traceback (most recent call last):
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/checker.py", line 164, in check
    result = await self._check(proxy, proto)
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/checker.py", line 237, in _check
    proxy.close()
  File "/home/reverb/.local/lib/python3.9/site-packages/proxybroker/proxy.py", line 332, in close
    self.writer.close()
  File "/usr/lib/python3.9/asyncio/streams.py", line 353, in close
    return self._transport.close()
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 700, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

But, I still see the proxies so i put them in to the proxychains file and then it says socket error without going through all the other proxies even though I have dynamic enabled. I'm really lost an need help, thanks in advance

**Comment by bluet** [comment]
As this project is not maintained by the original developer, we've forked ProxyBroker and continued maintaining the proxybroker2 project since 2020.
- https://github.com/bluet/proxybroker2
- https://github.com/constverum/ProxyBroker/pull/161

If anyone's interested, please join. We need more volunteers. :-)
