### ISSUE TITLE
trabl install end start

### ISSUE THREAD

**Issue by rulles22** [constverum/ProxyBroker#193]
1) # pip install -U git+https://github.com/constverum/ProxyBroker.git            
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting git+https://github.com/constverum/ProxyBroker.git
  Cloning https://github.com/constverum/ProxyBroker.git to /tmp/pip-req-build-1lmtNa
  Running command git clone -q https://github.com/constverum/ProxyBroker.git /tmp/pip-req-build-1lmtNa
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpRFg8S1
       cwd: /tmp/pip-req-build-1lmtNa
  Complete output (4 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 16, in <module>
      from importlib import import_module
  ImportError: No module named importlib
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpRFg8S1 Check the logs for full command output.

2) read a little

3)# pip3 install --upgrade setuptools && 
pip3 install --upgrade pip
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (59.6.0)
Collecting setuptools
  Downloading setuptools-62.6.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.8 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed setuptools-62.6.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (22.1.1)
Collecting pip
  Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 3.5 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-22.1.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv.

4)replay
pip install -U git+https://github.com/constverum/ProxyBroker.git
Collecting git+https://github.com/constverum/ProxyBroker.git
  Cloning https://github.com/constverum/ProxyBroker.git to /tmp/pip-req-build-e4kuzf9q
  Running command git clone --filter=blob:none --quiet https://github.com/constverum/ProxyBroker.git /tmp/pip-req-build-e4kuzf9q
  Resolved https://github.com/constverum/ProxyBroker.git to commit d21aae8575fc3a95493233ecfd2c7cf47b36b069
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: aiodns>=2.0.0 in /usr/lib/python3/dist-packages (from proxybroker==0.3.2) (3.0.0)
Requirement already satisfied: maxminddb>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from proxybroker==0.3.2) (2.2.0)
Requirement already satisfied: attrs==19.1.0 in /usr/local/lib/python3.10/dist-packages (from proxybroker==0.3.2) (19.1.0)
Requirement already satisfied: aiohttp>=3.5.4 in /usr/lib/python3/dist-packages (from proxybroker==0.3.2) (3.8.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

conclusion:
proxybroker find --types HTTP HTTPS --lvl High --countries US --strict -l 10 
/usr/local/lib/python3.10/dist-packages/proxybroker/cli.py:379: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/usr/local/bin/proxybroker", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/proxybroker/cli.py", line 380, in cli
    proxies = asyncio.Queue(loop=loop)
  File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

what to do how to be. HELP!!!

**Comment by bluet** [comment]
As this project is not maintained by the original developer, we've forked ProxyBroker and continued maintaining the proxybroker2 project since 2020.
- https://github.com/bluet/proxybroker2
- https://github.com/constverum/ProxyBroker/pull/161

If anyone's interested, please join. We need more volunteers. :-)
