### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

### ISSUE THREAD

**Issue by sova32** [constverum/ProxyBroker#194]
proxybroker find --types HTTPS SOCKS4 SOCKS5 --lvl High --countries UA --strict -l 100
/run/media/vadiki/D_238_GB_WD/Кибервойска/Анонимность/Proxy/proxy-scraper-checker-main/env/lib/python3.10/site-packages/proxybroker/cli.py:379: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/run/media/vadiki/D_238_GB_WD/Кибервойска/Анонимность/Proxy/proxy-scraper-checker-main/env/bin/proxybroker", line 8, in <module>
    sys.exit(cli())
  File "/run/media/vadiki/D_238_GB_WD/Кибервойска/Анонимность/Proxy/proxy-scraper-checker-main/env/lib/python3.10/site-packages/proxybroker/cli.py", line 380, in cli
    proxies = asyncio.Queue(loop=loop)
  File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

**Comment by bluet** [comment]
As this project is not maintained by the original developer, we've forked ProxyBroker and continued maintaining the proxybroker2 project since 2020.
- https://github.com/bluet/proxybroker2
- https://github.com/constverum/ProxyBroker/pull/161

If anyone's interested, please join. We need more volunteers. :-)

**Comment by sova32** [comment]
thankyou wery mach!

сб, 20 авг. 2022 г. в 20:04, BlueT - Matthew Lien - 練喆明 <
***@***.***>:

**Comment by inilho** [comment]
> 

you can update pythone version on your desktop

**Comment by sova32** [comment]
Python 3.11.3

пн, 29 мая 2023 г. в 09:29, Aldi Nurdianto ***@***.***>:
