### ISSUE TITLE
ProxyBroker Not Working - asyncio errors

### ISSUE THREAD

**Issue by justintimes** [constverum/ProxyBroker#20]
Hi, and thanks for ProxyBroker :)

I've been trying for a few days to get ProxyBroker to work but I've been unsuccessful. I installed as suggested and tried almost other apparent solution to get this working. Still nothing.

So, If I run this command I get these errors: I also tried via a mkvirtualenv. 

```
me@root:~$ proxybroker find --types HTTP
"Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/proxybroker-0.2.0b3-py3.5.egg/proxybroker/resolver.py", line 68, in get_real_ext_ip
    data = await resp.json()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 564, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/proxybroker", line 9, in <module>
    load_entry_point('proxybroker==0.2.0b3', 'console_scripts', 'proxybroker')()
  File "/usr/local/lib/python3.5/dist-packages/proxybroker-0.2.0b3-py3.5.egg/proxybroker/cli.py", line 310, in cli
    loop.run_until_complete(asyncio.gather(*tasks, loop=loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/proxybroker-0.2.0b3-py3.5.egg/proxybroker/api.py", line 149, in find
    ip = await self._resolver.get_real_ext_ip()
  File "/usr/local/lib/python3.5/dist-packages/proxybroker-0.2.0b3-py3.5.egg/proxybroker/resolver.py", line 70, in get_real_ext_ip
    raise RuntimeError('Could not get a external IP. Error: %s' % e)
RuntimeError: Could not get a external IP. Error: 
Exception ignored in: <coroutine object handle at 0x7ff66f244f68>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/proxybroker-0.2.0b3-py3.5.egg/proxybroker/cli.py", line 258, in handle
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed
me@root:~$
```

Please help

Thanks, I appreciate it.

**Comment by justintimes** [comment]
It's cool my friend, I simply changed this in resolver.py on line 65.

from

`with aiohttp.Timeout(self._timeout, loop=self._loop),\`

to

`with aiohttp.Timeout(20),\`

thanks again :)
