### ISSUE TITLE
TypeError: Queue.__init__() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by tainguyen7696** [constverum/ProxyBroker#200]
proxybroker find --types HTTP HTTPS --lvl High --countries US --strict -l 10
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\taing\AppData\Roaming\Python\Python311\Scripts\proxybroker.exe\__main__.py", line 7, in <module>
  File "C:\Users\taing\AppData\Roaming\Python\Python311\site-packages\proxybroker\cli.py", line 380, in cli
    proxies = asyncio.Queue(loop=loop)
              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Queue.__init__() got an unexpected keyword argument 'loop'

**Comment by enema-combatant** [comment]
It's Python 3.10 related.  You should only run this under <3.10, or 3.9 for example.

**Comment by miro5lav** [comment]
I got this error while trying to use faust library. I am using Python 3.11.8 though.

**Comment by whi7eboy** [comment]
![Screenshot 2024-03-13 030405](https://github.com/constverum/ProxyBroker/assets/157472710/22170762-8e29-4a3f-ae25-7bd522e62a46)
I done it under virtual env 3.5.9 python and had same issue
