### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

### ISSUE THREAD

**Issue by jfrenl** [constverum/ProxyBroker#203]
root@nextcounts:~/ProxyBroker-master# proxybroker find --types HTTP HTTPS --lvl High --countries US --strict -l 10
Traceback (most recent call last):
  File "/usr/local/bin/proxybroker", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/proxybroker/cli.py", line 380, in cli
    proxies = asyncio.Queue(loop=loop)
  File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary
root@nextcounts:~/ProxyBroker-master#

**Comment by PetrosM263** [comment]
Did you find the solution

**Comment by llama-for3ver** [comment]
Removing the instances (I found 3, in cli.py and api.py) seems to work.
