### ISSUE TITLE
Unexpected keyword

### ISSUE THREAD

**Issue by Justman100** [constverum/ProxyBroker#206]
> Traceback (most recent call last):
  File "bin/proxybroker", line 8, in <module>
    sys.exit(cli())

>  File "lib/python3.12/site-packages/proxybroker/cli.py", line 380, in cli
    proxies = asyncio.Queue(loop=loop)

> TypeError: Queue.__init__() got an unexpected keyword argument 'loop'

**Comment by pierrelouisdelx** [comment]
You need to use a python version < 3.10
