### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6

### ISSUE THREAD

**Issue by mi-pla** [constverum/ProxyBroker#31]
While trying any example from your website i get the following output:
`(python_virtual) C:\Users\Admin\Desktop\python_virtual>python helloworld.py
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client.py:526: D
eprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
Traceback (most recent call last):
  File "helloworld.py", line 29, in <module>
    main()
  File "helloworld.py", line 25, in main
    loop.run_until_complete(tasks)
  File "c:\users\admin\appdata\local\programs\python\python36-32\Lib\asyncio\bas
e_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\Admin\Desktop\python_virtual\lib\site-packages\proxybroker\api.
py", line 108, in find
    await self._run(self._checker.check_judges(), action)
  File "C:\Users\Admin\Desktop\python_virtual\lib\site-packages\proxybroker\api.
py", line 114, in _run
    await tasks
  File "C:\Users\Admin\Desktop\python_virtual\lib\site-packages\proxybroker\chec
ker.py", line 26, in check_judges
    await asyncio.gather(*[j.check() for j in self._judges])
  File "C:\Users\Admin\Desktop\python_virtual\lib\site-packages\proxybroker\judg
e.py", line 62, in check
    page = await resp.text()
  File "C:\Users\Admin\Desktop\python_virtual\lib\site-packages\aiohttp\client_r
eqrep.py", line 764, in text
    return self._content.decode(encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 5569: inval
id start byte

(python_virtual) C:\Users\Admin\Desktop\python_virtual>`

**Comment by erm3nda** [comment]
Its you sure that you are using python3 ?
