### ISSUE TITLE
RuntimeError: File descriptor 88 is used by transport

### ISSUE THREAD

**Issue by th3l0b3** [constverum/ProxyBroker#32]
Using Kali Linux 2.0

/usr/local/lib/python3.5/dist-packages/aiohttp/client.py:479: DeprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
Exception ignored in: <bound method DNSResolver._sock_state_cb of <aiodns.DNSResolver object at 0x7ffff355f978>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiodns/__init__.py", line 85, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 336, in add_reader
    self._ensure_fd_no_transport(fd)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 87 is used by transport <_SelectorSocketTransport fd=87 read=polling write=<idle, bufsize=0>>
Exception ignored in: <bound method DNSResolver._sock_state_cb of <aiodns.DNSResolver object at 0x7ffff355fa58>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiodns/__init__.py", line 85, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 336, in add_reader
    self._ensure_fd_no_transport(fd)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 88 is used by transport <_SelectorSocketTransport fd=88 read=polling write=<idle, bufsize=0>>

**Comment by wvengen** [comment]
Seing this also with https://github.com/kulaj/ProxyBroker/commit/a797fb98390e219360c1f2cd80eea53cb06309b4 (where async warning is fixed).
aiodns 1.1.1

```
Exception ignored in: <bound method DNSResolver._sock_state_cb of <aiodns.DNSResolver object at 0x7f982ce2a1d0>>
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.5/site-packages/aiodns/__init__.py", line 85, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 336, in add_reader
    self._ensure_fd_no_transport(fd)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 103 is used by transport <_SelectorSocketTransport fd=103 read=polling write=<idle, bufsize=0>>
```

**Comment by erm3nda** [comment]
Same for me. I am using aiodns==1.1.1 but sometimes i get the File descriptor error :-/

**Comment by gabrielgradinaru** [comment]
This is an issue related to aiohttp which has been fixed: 
https://github.com/aio-libs/aiohttp/issues/1848
