### ISSUE TITLE
Error on launch.

### ISSUE THREAD

**Issue by Serasar** [constverum/ProxyBroker#42]
Got an error:

`Traceback (most recent call last):
  File "/usr/local/bin/proxybroker", line 11, in <module>
    load_entry_point('proxybroker==0.2.0b3', 'console_scripts', 'proxybroker')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/proxybroker/__init__.py", line 28, in <module>
    from .proxy import Proxy
  File "/usr/local/lib/python3.4/dist-packages/proxybroker/proxy.py", line 35
    async def create(cls, host, *args, **kwargs):
        ^
SyntaxError: invalid syntax
`
What might be the reason?

**Comment by Codehimn** [comment]
README.rst =

Requirements
## Python 3.5 or higher
