### ISSUE TITLE
Can't run ProxyBroker under Windows XP

### ISSUE THREAD

**Issue by Shazgul** [constverum/ProxyBroker#51]
`C:\Python34\Scripts>proxybroker.exe
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\proxybroker.exe\__main__.py", line 5, in <module>
  File "c:\python34\lib\site-packages\proxybroker\__init__.py", line 28, in <mod
ule>
    from .proxy import Proxy
  File "c:\python34\lib\site-packages\proxybroker\proxy.py", line 35
    async def create(cls, host, *args, **kwargs):
        ^
SyntaxError: invalid syntax`

Getting this Error when i try to start Proxybroker from Script Folder under Windows XP - Any Solution on this?

**Comment by erm3nda** [comment]
RTFM

Requirements

    Python 3.5 or higher
    aiohttp
    aiodns
    maxminddb
