### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by DataPools** [constverum/ProxyBroker#61]
I sometimes get this error when using proxybroker:
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 710, in _create_direct_connection
    local_addr=self._local_addr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 651, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 638, in create_connection
    yield from self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 387, in __iter__
    return self.result()  # May raise too.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/selector_events.py", line 411, in _sock_connect
    sock.connect(address)
OSError: [Errno 65] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 737, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Can not connect to ifconfig.co:443 [No route to host]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    main()
  File "test.py", line 23, in main
    loop.run_until_complete(tasks)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/proxybroker/api.py", line 150, in find
    ip = await self._resolver.get_real_ext_ip()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/proxybroker/resolver.py", line 100, in get_real_ext_ip
    session.get(self._pop_random_ip_host()) as resp:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 65] Cannot connect to host ifconfig.co:443 ssl:True [Can not connect to ifconfig.co:443 [No route to host]]
```

**Comment by Gallaecio** [comment]
I got a similar one (same exception, different errno, same host):

```
Traceback (most recent call last):
  File "/usr/local/bin/proxybroker", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/proxybroker/cli.py", line 366, in cli
    loop.run_until_complete(asyncio.gather(*tasks, loop=loop))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/proxybroker/api.py", line 150, in find
    ip = await self._resolver.get_real_ext_ip()
  File "/usr/local/lib/python3.6/site-packages/proxybroker/resolver.py", line 100, in get_real_ext_ip
    session.get(self._pop_random_ip_host()) as resp:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 383, in connect
    .format(key, exc.strerror)) from exc
aiohttp.client_exceptions.ClientConnectorError: [Errno 101] Cannot connect to host ifconfig.co:443 ssl:True [Can not connect to ifconfig.co:443 [Network is unreachable]]
```

I guess this is an unavoidable exception, but it should probably be handled more gracefully. Maybe a simple:

```
try:
    triggering_call()
except aiohttp.client_exceptions.ClientConnectorError:
    pass
```
