### ISSUE TITLE
cracks me up

### ISSUE THREAD

**Issue by netcrave** [constverum/ProxyBroker#76]
```
 erratic@shells  ~/ProxyBroker   master  python setup.py install
^CTraceback (most recent call last):
  File "setup.py", line 61, in <module>
    test_suite='tests',
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/erratic/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 866, in resolve
    replace_conflicting=replace_conflicting
  File "/home/erratic/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1146, in best_match
    return self.obtain(req, installer)
  File "/home/erratic/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1158, in obtain
    return installer(requirement)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/dist.py", line 528, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 661, in easy_install
    not self.always_copy, self.local_index
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/package_index.py", line 656, in fetch_distribution
    self.find_packages(requirement)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/package_index.py", line 489, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/package_index.py", line 829, in scan_url
    self.process_url(url, True)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/package_index.py", line 350, in process_url
    f = self.open_url(url, tmpl % url)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/package_index.py", line 768, in open_url
    return open_with_auth(url, self.opener)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/package_index.py", line 969, in _socket_timeout
    return func(*args, **kwargs)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/package_index.py", line 1088, in open_with_auth
    fp = opener(request)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/ssl_support.py", line 161, in https_open
    lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/home/erratic/.local/lib/python2.7/site-packages/setuptools/ssl_support.py", line 174, in connect
    (self.host, self.port), getattr(self, 'source_address', None)
  File "/usr/lib/python2.7/socket.py", line 566, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```

**Comment by constverum** [comment]
> Requirements
> **Python 3.5 or higher**
