### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Dummy-1'.

### ISSUE THREAD

**Issue by laoniustudio** [constverum/ProxyBroker#81]
I am using django, when run manage.py runserver have this errors, please help
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10a74b6a8>
Traceback (most recent call last):
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/sun/Documents/pycharm_project/AlliedRateChangeWebBackend/AlliedRateChangeWebBackend/AlliedRateChangeWebBackend/urls.py", line 21, in <module>
    path('orbitz/',include('orbitz.urls')),
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/sun/Documents/pycharm_project/AlliedRateChangeWebBackend/AlliedRateChangeWebBackend/orbitz/urls.py", line 2, in <module>
    from .views import GetRateView,GetDefaultPriceView,PostDataView,PostRezPower,AccountInfo,LoginAccount,LoginSetting,ConnectRezlight
  File "/Users/sun/Documents/pycharm_project/AlliedRateChangeWebBackend/AlliedRateChangeWebBackend/orbitz/views.py", line 6, in <module>
    from .getProxies import ProxyFetch
  File "/Users/sun/Documents/pycharm_project/AlliedRateChangeWebBackend/AlliedRateChangeWebBackend/orbitz/getProxies.py", line 2, in <module>
    from proxybroker import Broker
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/proxybroker/__init__.py", line 29, in <module>
    from .judge import Judge  # noqa
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/proxybroker/judge.py", line 14, in <module>
    class Judge:
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/site-packages/proxybroker/judge.py", line 18, in Judge
    ev = {'HTTP': asyncio.Event(), 'HTTPS': asyncio.Event(),
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/asyncio/locks.py", line 226, in __init__
    self._loop = events.get_event_loop()
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/asyncio/events.py", line 678, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/Users/sun/anaconda/envs/ratechange/lib/python3.6/asyncio/events.py", line 584, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-1'.

**Comment by anmv** [comment]
I have same problem!

**Comment by therajahilda** [comment]
I have a same problem

**Comment by gante** [comment]
I suspect it is related to this issue: https://stackoverflow.com/questions/41594266/asyncio-with-django/46140106

**Comment by Mass1998** [comment]
Anyone get this fixed?

**Comment by izzetemredemir** [comment]
I have same problem on Flask
